---
title: "marlin-paper-notes"
author: "Dan Ovando"
date: "4/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

what dooes the overlap tradeoff curve look like? 

Suppose you close off 30% of an area in an MPA

Then plot conservation outcome on y-axis, degree of overlap between target and bycatch species on the x axis. When overlap is one, conservation benefit should be maxed. Then overlap is perfeclty anticorrelated, if effort concentrates, conservation should be at some negative minimum. If concentration doesn't happen, then conservation effect should be zero. If overlap is uncorrelated... unclear?

MPA literature has been dominated by single-species model covering homogemous habitat without any technical interactions across multiple fleets and species. 

@hastings2017 assumes that adults are stationary, larvae are perfectly mixed, age structure can be ignored, density dependence at time of settlement. Same harvest rate outside reserve. 

static spatial, dynamic spatial , input / output controls, gear

If there is perfect overlap, then improvement in coservation outcome should be a straight positive function of area protected. If there is no overlap, then 


# what's the angle?

Smith et al and references therein make the basic case pretty damn clear: when species move a lot and when habitats overlap, static MPAs don't work as well as dynamic. There are other nuances in there but that kind of summarizes a lot of it

so what are the specific angles this paper can take

- When do static closures go from "less effective" to "not effective"

Those papers point out "less effective" since max species = 2 to 4. But, we're seeing here that non-trivial case of net loss? But is it really non-trivial? like 15% of simulations with more than 10%? though that number is a lot bigger if you're basically asking "did it help"

So that's certainly an angle that's unexplored here. 


- Yet another comparison to active fisheries management

Tying more directly to fisheries management, compare to say a TAE, in terms of units bycatch saved per unit of target catch lost 

Could also do the dynamic comparison, though that one is a bit boring to me since it's sort of self evident, so question is the wedge?

Could also ask something about how much would gear efficiency have to change, though it feels like that would be so detail derived it would be hard to make general

- Value of information




- A more tactical evaluation

Lean in a bit more to an area and specific existing or proposed MPAs with best estimates of bycatch risk / target fleets in space. 

The cleanest to what we have now, but also the most contentious / work. If we go with actual MPAs, really need to dial in the species and fleets, which we're pretty close to do be honest, but also the habitats etc. 

Though there is a more general question like "what's the best outcome you could get for bycatch with static closures in a place that looks like the WCPO". Or rather what design gets you the best outcome. Now you'd have to put a constraint on that, say total catches can't decline by more than xx%?

Hmm I like this one sort of

- incentives piece around bycatch
incentive to fish and incentive to protect

So this isn't the odd rare turtle, these are valuable sharks


## optimization

similar SIR approach... why not just get it running first

Yields: sum of revenue of target species: or if you just say revenue, then you can manipulate prices to get desired impact: if you say that bycatch literally has no value then just set price to 0, or negative. 

biodiversity: B/K of all species (for now): average or sum? Sum I think, since you'd rather have all at 0.5 than half at 0 and half at 1

yield_weight: do you have MSY for all species? I don't think so, and gets crazy complicated to think about MSY once you start messing with technical interactions etc. So you just need something to weight the marginal value of both. 

So, for every step, you'll have N candidate cells, each with a marginal yield effect and a marginal biodiversity effect. You then need to rank each cell by the objective function. Need some function to convert yield and biomass into comparable units then. So just center and scale? alpha then controls the relative weight of a standard deviation increase in yield relative to a standard deviation increase in biodiversity? Issue there: once you're down to the last cell this won't work. Dividing by max caps both at 1, but no limit to the loss there... Rescale to be positive? yield - min(yield) + 1e-3 will ensure the min value is 1e-3, then scaling by max of that vector will make the max 1, so now everything has the same range. Oh, or just use scaes::rescale to put both on range of 0 to 1. 

Is that going to have weird behavior rescaling at every iteration like that? i.e. the effective value of alpha will change depending on the scale of the biomass and yield. Setting alpha to 1 will maximize yields, setting it to 0 will maximize biodiversity, what does setting to 0.5 mean? value the best yield cell as much as the best biomass cell. 

Seems good enough for now. So doing it this way, you only have to iterate over the weight, no different objective function shapes

So what are you optimizing? Location and size or just location? In theory, you can save some computation time by stopping the optimization when the objective function starts to consistently decline. But, since there might be multiplie maxima here, that could get tricky, and wouldn't allow you to look at tradeoff wedges. So...

- for each weight
- for each range of MPA sizes
- find the optimal MPA configuration. 
- Not too bad!

## what are you comparing optimization to

OK, you have some optimized results, so what. On the one hand, you can examine to what extent given this case study, tradeoffs across species or across yields are inevitable or just gotta find the right network. 

From there though, can also compare "optimal" to "realistic"

Design strategies
1. Assign protection by SSB / SSB0 weighted abundance in space (protect the highest concentrations of the most threatened species)
2. Assign protection by bycatch rates (distribution of biomass bycatch / biomass target)
3. Assign protection by targeting fishing effort
4. Assign protection by avoiding fishing effort

Knowledge states
1. Degrees of accuracy over the thing being measured (i.e. error in the design strategy)

2. Number of species considered (e.g. design around only 2 bycatch species instead of all)

3. über naive: just close off random patches up to a specified size

We then plot these points in objective function space and compare to the efficiency frontier / consider frequency and magnitude of conservation and economic tradeoofs

The question all this is answering: how sensitive are conservation and economic outcomes to design strategy / uncertainty when there are technical interactions and heterogeneity in habitat? The first stage is teeing up the idea that beyond conservation / yield tradeoffs, as you increase habitat heterogeneity with technical interactions you increase the potential for conservation tradeoffs. But, the degree is going to be super context dependent, so to dive in a bit we then focus on this case study of the particular species / habitat overlap in the WCPO. Further work might reveal more generalities in this, but htis is basically getting a sense for the potential magnitude of the challenge. 


OK, this is actually coming together! You should run the same design / knowledge states for the broader range of simulated habitats. That will make the point nice and clearly. 

But, that begs the question of, is it an inevitable tradeoff, or just a case of poor design. That requires optimization. But, optimization is very computationally intensive. To examine this point then, we repeated the exercies, but with a specific case study where we hold habitat as constant, but redo the exercise conditional on constant habitat. We can then see to what extent tradeoofs persist, and ideally come up with some way of comparing the case study habitats to the metric of habitat heterogeneity in the full simulations. Case study also demonstrates that its a real thing: not making up the idea of different habitat use

This might actually be a cool paper. Proc B?

Idea: what ig instead of local or global, you have a parameter that says how many metapopulations there are. 1 says global density dependence, patches says one per patch. you then divide up the patches in equal aquares based on that, and calculate density dependence on that level. 
