---
format: pdf
editor: visual
---

Dear Editors, 

We are writing to submit our manuscript titled "Simulating Benefits, Costs, and Tradeoffs of Management Policies in Marine Social-Ecological Systems" for consideration at Ecological Applications. Spatial management policies such as marine protected areas are increasingly being looked to to help manage and conserve marine ecosystems. However , designing
spatial management strategies to achieve desired objectives -- which may
include recovery and resilience of overfished species, increased food
production and economic well being, and equitable distribution of
benefits - is not straightforward due to the complex, dynamic, and opaque nature of marine social-ecological systems. 

In this paper we present a bio-economic model intended to facilitate the study and design of marine management policies called [`marlin`](https://github.com/DanOvando/marlin/). `marlin` allows users to efficiently simulate the dynamics of multiple species and fishing fleets across space and time, using realistic representations of life history, economic decision making, and movement dynamics. 

We show in this paper how `marlin` can be used to help inform policy decisions related to the design and placement of marine protected areas through two case studies, and discuss how this tool can help answer a wider array of research and management questions in marine social-ecological systems. 

Thank you for your consideration, 

Dan Ovando & Co-Authors





