---
title: "Efficient Simulation of Economic and Ecological Dynamics for Marine Spatial Planning"
author:
    - Daniel Ovando
    - Darcy Bradley
    - Lennon Thomas
    - Echelle Burns
date: "`r Sys.Date()`"
format:
  pdf:
    toc: true
  html: default
  docx: default
execute:
  echo: false
  message: false
  warning: false
bibliography: references.bib
params:
  params:
  run_name: ["v1.1"]
---

```{r setup}
#| echo: false
#| message: false

source(here::here("scripts", "00_setup.R"))

theme_set(marlin::theme_marlin())

sci_to_com <- taxize::sci2comm(unique(marlin_inputs$scientific_name)) %>% 
  bind_rows(.id = "critter") %>% 
  pivot_longer(everything(),names_to = "critter",values_to = "common_name") %>% 
  mutate(common_name = stringr::str_to_title(common_name))

results_files <- list.files(file.path(results_path))

rdses <- results_files[str_detect(results_files,'.rds')]

walk(rdses,~assign(str_remove(.x,".rds"), read_rds(file.path(results_path,.x)), envir = .GlobalEnv)) #load and assign all .rds objects in the appropriate results folder

rdatas <- results_files[str_detect(results_files,'.Rdata')]

walk(rdatas, ~load(file.path(results_path,.x), envir = .GlobalEnv)) # load results into global environment

```

need to contrast with SEAPODYM



<!-- Single column, double line spaced -->
<!-- Within the word count (no more than 7000-8000 words for Standard Articles, 3000-4000 words for Applications and Practical Tools) -->
<!-- Continuous line and page numbering throughout -->
<!-- Clearly defined manuscript structure as standard: Author details, Abstract (must be numbered 1-4 according to Manuscript Specifications), Keywords, Introduction, Materials and Methods, Results, Discussion, Figures and Tables with captions -->
<!-- Figures and Tables can be embedded within the text where referenced to facilitate reviewing -->
<!--         Author Contributions (if >1 author – see Authorship Policy). -->
<!--         Statement of where you intend to archive your data -->



## Introduction

Communities around the world are increasingly looking to spatial
strategies for managing marine ecosystems. For example, the "30x30"
movement calls for implementation of marine protected areas, a form of
spatial management, across 30% of the world's oceans by 2030. While the
objectives of individual spatial management strategies vary widely,
spatial management strategies are often supported based on their ability
to provide protection to broad swaths of marine ecosystems with one
management action, with potentially fewer costs and complications than
for example assessing, setting, and enforcing catch quotas for
individual species.

However, the design of spatial management strategies faces numerous
challenges. Marine ecosystems are highly dynamic and opaque, and
extractive entities such as fishing fleets respond to changes in marine
ecosystems in highly complex ways. These dynamics post challenges even
for single-species assessment and management strategies [@field2006a],
which are only amplified when we consider management policies
specifically designed around spatial features in the oceans. For
example, policies such as MPAs designed for both conservation and food
security must consider factors such as the optimal size and placement of
a protected area network given a wide array of life history,
exploitation levels, fleet dynamics, and preferred habitats, all of
which may change over time, particularly given the impacts of climate
change.

These challenges are amplified by the fact that our knowledge regarding
the design and implementation of spatial management strategies such as
MPAs is largely based on theoretical studies; the size of protected
areas [@ovando2021a] and time required[@nickols2019] to see substantial
effects from many MPAs means that we have relatively little empirical
evidence as to their large-scale effects under a range of
social-ecological settings [@mcclanahan2021].

Many models have been developed to support the theory and design of
spatial management strategies [@fulton2015]. However, they have tended
to fall into one of either highly complex and tactical models designed
for use in a specific location, or to be highly stylized representations
intended to provide theoretical insights with less relevance for highly
specific design questions. This complex landscape presents a challenge
to stakeholders charged with marine spatial planning exercises lacking
accesible models suited for more tactical applications, and a barrier to
the scientific community, wherein comparisons across spatial management
simulation studies are clouded by discrepancies in underlying model
structures beyond differences in the core phenomenon in question.

In part to help address this challenge, we present here a novel
bio-economic modeling framework called `marlin` that allows for
efficient simulation of spatio-temporal biological and economic
dynamics. `marlin` allows users to simulation the impacts spatial
policies such as MPAs across a range of species targeted by various
fleets across heterogeneous and dynamic seascapes. Here we present the
core methods and functionality of this framework, and demonstrate its
use in two xx case-study applications. In the first, we show how
`marlin` can be used to assess critical drivers for positive outcomes
and unintended consequences of MPAs as a bycatch-mitigation strategy. In
the second, we present a more tactical application, demonstrating how
`marlin` can be used to compare and design MPA networks to achieve
societal objectives.

-   MPAs increasingly part of plan

-   A model based field - hard to do experiments at the time and scale
    needed

-   many models out there, but challenges

    -   highly stylized

    -   highly tactical

-   We present a general tool for modeling spatial dynamics of fished
    populations and fishing fleets, with a focus on MPAs

-   We present two case studies showing the utility of this approach

    -   habitat heterogeneity and bycatch

    -   MPA optimization

-   Basis for improved "what if" testing of MPA scenario

## Methods

Models of MPAs span a wide range of complexity, from simple analytical
tools to end-to-end ecosystem models [@fulton2015]. `marlin` follows a
"models of intermediate complexity" (MICE) philosophy [@plagányi2014]
targeted specifically around the role of technical interactions across
species. Many MPA models simulate the impacts of MPAs on a
single-species level [@ovando2021a]. This can be useful for for example
examining the ways in which species-specific life history traits
interact with fleet dynamics to influence MPA outcomes. However, bycatch
problems are driven by technical interactions, in which fishing effort
for a target species incidentally captures another species. `marlin`
accounts for this by allowing the user to simulate an arbitrary number
of fleets capable of catching an arbitrary number of species in a
spatial area. Different fleets can place different economic value on
different species, while also having species-specific selectivity
functions. This allows us to simulate bycatch dynamics of MPAs in
pelagic ecosystems.

Below we provide a summary of the `marlin` model, as well as details of
the generalized simulation exercises and case study analyses.

### Fleet Dynamics

The key feature of `marlin` for the purposes of this project is the
ability to capture technical interactions across species. While marlin
does not simulate species interactions, fishing fleets in `marlin` are
capable of targeting and affecting multiple species simultaneously. This
allows us to capture for example the potential impacts of displacement
of effort from one area into another across multiple species.

A fishing fleet or *metier* is defined in `marlin` by a total pool of
effort that can have different catchability, prices, and selectivity for
individual species within a simulation. For example, both a longline and
purse seine fleet may capture bigeye (*Thunnus obesus*) and skipjack
(*Katswamus pelamus*), but the longline fleet is much more likely to
catch bigeye than skipjack, and *vice versa*. Each fishing fleet
generates catches, revenues, and profits from individual species that it
targets, and makes decisions based on its total objective function
across all species.

Revenues *R* for fleet *f* in time step *t* are given by

$$
 R_{t,p,f} = \sum_s^S \sum_a^A \Pi_{s,f}\frac{\alpha_{a,s,f}q_{s,f}E_{t,p,f}}{F_{t,p,s,a}} \times Y_{t,p,s,a}
$$

where *p* is patch, *s* is species, *a* is age, $\alpha$ is selectivity
at age, *q* is catchability , *F* is total fishing mortality, $\Pi$ is
price per unit weight, and *Y* is total catches.

$$
Y_{t,p,s,a} = \frac{F_{t,p,s,a}}{z_{t,p,s,a}} \times b_{t,p,s,a} \times (1 - e^{-z_{t,p,s,a}}) 
$$

where *F* is total fishing mortality, given by

$$
F_{t,p,s,a} = \sum_f^F\alpha_{a,s,f}q_{s,f}E_{t,p,f}
$$

Selectivity $\alpha$ is modeled through a logistic form per

```{=tex}
\begin{equation}
\alpha_{a,s,f}=\frac{1}{(1 + e^{-log(19)\times\frac{l_{a,s} - l^{sel}_{s,f}}{\delta^{sel}_{s,f}}})}
  (\#eq:sel)
\end{equation}
```
where $l$ is length at age, $l^{sel}$ is the length at 50% selectivity,
and $\delta$ is the difference between the length at 50% selectivity and
the length at 95% selectivity.

*z* is total mortality given by

$$
 z_{t,p,s,a} = F_{t,p,s,a} + m_{s,a}
$$

Where *m* is natural mortality.

This means that each species experiences a total mortality at age in a
time step in a patch, individual fractions of which are portioned off as
catches and subsequently revenues for each fleet. Given revenues, we
then calculate profits $\phi$ per

$$
\phi_{t,p,f} = R_{t,p,f} - c_f(E_{t,p,f} + 1)_{t,p,f}
^{1.3}
$$

where *c* is cost per unit effort and, the 1.3 exponent is in the manner
of @costello2016a . The addition of one to the total effort is to
constrain the value to be greater than 1, preventing undesired behavior
where fishing effort actually gets less expensive if total effort is
less than 1.

The important feature here then is that the revenues and profits for a
given fleet are a function of the prices and catchability of individual
species, but that mortality itself is independent of price. So, a fleet
that has selectivity and catchability greater than zero can exert
fishing mortality on a species even if it obtains no value from that
species.

Each fishing fleet then decides how to allocate its effort in space
based on one of four possible spatial allocation strategies. The ideal
free distribution (IFD) is the standard method for distributing fishing
fleets in spaces (see @gillis2003 and references therein). However, the
IFD presents a number of complications for our study. First, in order to
simplify the assessment of the impacts of different fishing mortality
rates we simulate scenarios with a fixed total pool of effort. As MPAs
change the spatial distribution of profits though, the total amount of
effort required to satisfy the IFD may not equal the total amount of
effort required by the model. Second, even if we were to implement the
IFD for a single fleet, the model is capable of tracking multiple fleets
at once. This means that the IFD for a single fleet would be a
game-theoretic outcome of the actions of each of the individual fleet
conditional on the actions of all other fleets. While possible to
implement this would slow down our model runs to the point of
practically preventing large-scale evaluation of the effects of MPAs on
bycatch.

As such we explored a series of "next best" fleet distribution
algorithms. While not the IFD in any individual time step, over time
they start to approximate the IFD, as each assumes that fleets base
their decisions for the current time step on the outcomes in the prior
timestep, meaning that the impacts of the actions of other fishing
fleets are somewhat internalized. The four possible fleet distribution
algorithms are

1.  Revenue per unit effort (RPUE): The fleet distributes itself in
    space based on revenue per unit effort
2.  Revenue: The fleet distributes itself in space based on revenue
3.  Profit per unit effort (PPUE): The fleet distributes itself in space
    based on profit per unit effort
4.  Profit: The fleet distributes itself in space based on profit

Revenue based spatial distribution is not likely to be very realistic .
However, due to the complexity of parameterizing cost functions fleet
dynamics are often evaluated based on yield or revenue alone, and so we
include those scenarios here to evaluate the potential implications of
this choice. The decision on whether to allocate the fleet based on
absolute or relative (per unit effort) is more complex. When effort
represents the actions of separate and individual fishing actors (e.g.
independent fishing vessels), a per-unit-effort strategy may be more
realistic, in which fishers distribute themselves based on the expected
catch of their individual efforts [@hilborn1987]. Conversely, a system
defined by a sole owner seeking to maximize total profits might be
better represented by a fleet model based on total profits

### Population Model

The underlying population model used is an age structured single-species
model in the manner of @ovando2021a.

For the population model, numbers *n* at time *t* for age *a* are given
by

```{=tex}
\begin{equation}
n_{t,p,s,a}=\begin{cases}
      = BH(ssb_{t-1,p,s,a}) & \text{if $a = 1$}\\
     = n_{t-1,p,s,a-1}e^{-(z_{t-1,p,s,a-1}}, & \text{if $1< a < max(age)$}\\
     =  n_{t-1,p,s,a}e^{-(z_{t-1,p,s,a})} + n_{t-1,a-1}e^{-(z_{t-1,p,s,a-1})}, & \text{if $a = max(a)$}
  \end{cases}
  (\#eq:pop)
\end{equation}
```
where *BH* is the Beverton-Holt recruitment function, *ssb* is
spawning-stock-biomass.

where $l_a$ is the mean length at at age, $l_sel$ is the length at which
on average 50% of individuals are selected by the fishery, and
$\delta_{sel}$ are the additional units of length at which on average
95% of fish are selected by the fishery.

*ssb* is calculated by converting age to mean length, calculating weight
at age, maturity at age, and then calculating spawning stock biomass as
the sum of spawning potential at age in a given time step.

```{=tex}
\begin{equation}
  l_{a,s} = l\infty_s\left(1 - e^{-k_s(a - a0_{s})}\right)
  (\#eq:len)
\end{equation}
```
Biomass *b* at age is then given by

```{=tex}
\begin{equation}
  b_{a,s} = wa_s \times l_{a,s}^{wb_s}
  (\#eq:weight)
\end{equation}
```
and maturity *mat* is calculated as

```{=tex}
\begin{equation}
  mat_{a,s} = \frac{1}{(1 + e^{-log(19)\times\frac{l_{a,s} - lmat_s}{{\delta}mat_s}}}
  (\#eq:mat)
\end{equation}
```
where $l_{mat}$ is the length at which on average 50% of individuals are
sexual maturity, and $\delta_{mat}$ is the units of length beyond
$l_{mat}$ at which on average 95% of fish are sexually mature.

Spawning stock biomass at time *t* is then calculated as

```{=tex}
\begin{equation}
  ssb_{t,p,s} = \sum_{a=1}^Aw_{a,s,t}^{\gamma_s} mat_{t,a} n_{t,p,s,a}
    (\#eq:ssb)
\end{equation}
```
#### Recruitment {.unnumbered}

Recruitment follows Beverton-Holt dynamics. We do however allow for
three variants in the timing of density dependence:

1.  Global density dependence: Density dependence is a function of the
    sum of spawning biomass across all patches, and recruits are then
    distributed according to habitat quality

```{=tex}
\begin{equation}
n_{t,p,s,a = 1} = \left(\frac{0.8{\times}\sum_{p=1}^P{r0_{p}}\times{h}\times\sum_{p=1}^P{ssb_{t-1,p}}}{0.2\times{\sum_{p=1}^Pssb0_p}\times(1 - h)+(h - 0.2)\times{\sum_{p=1}^Pssb_{t-1,p}}}\right)\times {hab_p}
  (\#eq:dd2)
\end{equation}
```
where *hab* is a vector of recruitment habitat quality by patch degined
by

$$hab_p = r0_p / \sum_p^P{r0_p}$$ 2. Local density dependence: Density
dependence occurs independently in each patch and recruits are retained
in their home patch.

```{=tex}
\begin{equation}
  n_{t,p,s,a = 1,p} = \left(\frac{0.8{\times}r0_{s,p}\times{h_s}\times{ssb_{t-1,p,s}}}{0.2\times{ssb0_{p,s}}\times(1 - h_s)+(h_s - 0.2)\times{ssb_{t-1,p}}}\right)
  (\#eq:dd1)
\end{equation}
```
3.  Local density dependence then disperse: Density dependence occurs
    independently in each patch and recruits are then dispersed.

```{=tex}
\begin{equation}
  n_{t,p,s,a = 1,p} = \left(\frac{0.8{\times}r0_{s,p}\times{h_s}\times{ssb_{t-1,p,s}}}{0.2\times{ssb0_{p,s}}\times(1 - h_s)+(h_s - 0.2)\times{ssb_{t-1,p}}}\right)\times \boldsymbol{d^l} \times \epsilon_t
  (\#eq:dd3)
\end{equation}
```
where **d^l^** is the recruitment movement matrix

4.  Post-dispersal density dependence: Larvae are distributed throughout
    the system, and then density dependence occurs based on the density
    of adult biomass at the destination patch.

```{=tex}
\begin{equation}
  larv_{t,p} = ssb_{t-1} \times\boldsymbol{d^l}
  (\#eq:larvmove)
\end{equation}
```
```{=tex}
\begin{equation}
n_{t,a = 1,p} = \left(\frac{0.8{\times}r0_{p}\times{h}\times{larv_{t,p}}}{0.2\times{ssb0_p}\times(1 - h)+(h - 0.2)\times{larv_{t,p}}}\right) \times \epsilon_t
  (\#eq:dd4)
\end{equation}
```
#### Dispersal

`marlin`'s movement dynamics are based on a continuous-time Markov
chain, as described in @thorson2021a. Within this framework, the model
allows for movement to be broken down into three components of
*diffusion*, *advection* (follow currents), and *taxis* (active movement
towards say a preferred habitat).

xx movement equations xx

While this approach to movement simulation is not commonly seen in the
marine modeling literature, it has numerous advantages that warrant its
seeming complexity. First, when only diffusion is present, the model
will generalize to the familiar dynamics of a Gaussian dispersal kernel
xx check this xx. However, the time component *t* in equation xx allows
the movement model to be run on arbitrary time steps while preserving
its behavior.

Second, the *advection* component allows users to input useful features
such as the outputs of ROMs models.xxx

Third, the *taxis* model allow for more active habitat choices by
species, allowing us to simulate both preferences of species in space
and time efficiently.

In this way then, `marlin` allows users to run anything from a simple
Gaussian dispersal kernel up to a system governed by species that
passively diffuse around a dynamic thermal range

Lastly, this form has the advantage that the parameters are directly
estimable from real data. So, if provided with say CPUE data and a
tagging study, users can estimates the movement parameters in the same
manner as @thorson2021, and then pass their estimated parameters to
`marlin` for simulation.

### Rule-of-thumb MPA Design Strategies

MPA design is governed by two general parameters: the number of cells to
place inside an MPAs, and the design strategy used to place the MPAs.

We consider `r n_distinct(experiment_obj$placement_strategy)` different
MPA placement strategies.

1.  Depletion: MPA locations are prioritized in proportion to the
    spawning stock biomass of the most depleted species pre-MPA. So,
    patches with high spawning biomass of highly depleted species are
    prioritized over patches with high spawning biomass of lightly
    depleted species.

2.  Rate: MPAs are placed in based on the pre-MPA depletion-weighted
    catch relative to the total catch in a patch. So, patches with high
    rates of catch of depleted species relative to total catch are
    prioritized.

3.  Avoid_fishing: MPAs locations are prioritized inversely to fishery
    catches. So, patches with low catches are prioritized over patches
    with high catches.

4.  Target_fishing: MPAs locations are prioritized proportionally to
    fishery catches. So, patches with high total catches are prioritized
    over patches with low catches.

5.  Area: For the "area" strategy, we simply assign patches in
    sequential order until the desired total MPA size is reached.

<!-- The information used to inform each MPA design strategy (except area) -->

<!-- can include a multiplicative observation error term $\sigma_{obs}$ where -->

<!-- $$information \sim lnorm(data,\sigma_{obs}) $$ -->

<!-- For example, for the depletion scenario, $\sigma_{obs}$ controls the -->

<!-- accuracy of the spatial depletion data used to prioritize MPA placement. -->

## Reference Points

A note here WHy no reference points? The problem: Fmsy and MSY are
selectivity dependent, and once we allow for different fleets with
different selectivities that critical can move in space, that movement
affects the net selectivity and fishing mortality on the population.

Bmsy is also affected, since if selectivity is very low, you might need
more biomass of immature individuals relative to less biomass of more
mature individuals; a biomass of X can be more or less reproductively
productive depending on the size / age makeup of that biomass.

SSBmsy is slightly more conserved, as over the long term the key things
is the flow of recruits, so we do provide an option for that

There are many different strategies for estimating reference points
conditional on selectivity and regimes, see references. We leave it to
users to find relevant reference point as required by their methods on
their own, using the sort of MSE examples available in the package.

## MPA Optimization

Our MPA optimization algorithm seems to create an MPA network that
maximizes an objective function, given by

$$obj_p = \Phi \times scale(\sum_f^F \boldsymbol{\phi_{f,p}}) + (1 - \Phi)  scale(\boldsymbol{\sum_s^S\frac{ssb_s}{ssb0_{s,p}}})$$

Where *scale* rescales the values to be between 0 and 1 such that the
weight parameter is comparable between vectors. The algorithm works by
first assigning every patch in the system to an MPA. For the first
round, the algorithm then calculates the equilibrium objective function
value resulting from sequentially removing each individual patch from
the MPA network. The cell whose removal from the MPA produces the
highest objective function value is then removed from the MPA network,
and the marginal value of the objective function each of the remaining
cells from the last steps are then stored. For the next steps, we
sampled 25% of the remaining MPA cells with probability proportional to
their marginal contribution to the objective function in the prior
iteration, selecting the cell whose removal produces the highest total
objective function as the cell to remove from the network, and updating
the marginal value of the sampled-but-not-selected cells. This in
essence is a sampling-importance-resampling algorithm. The algorithm
continues until no more cells are left in the MPA. This then provides
for a given objective weighting value $\Phi$ the near-optimal MPA
network at every MPA size from 0 to 100%. We say "near" as they is some
path dependency here, in that for example the network that maximizes the
objective function with 40% of the MPAs does not necessarily contain the
optimal network at 30%. However, the reversed nature of the algorithm,
starting at 100% MPA coverage and working better, produces a more stable
network with regards to this problem than starting at 0% and growing to
100%.

## Generalized Experiments

Two features of marine ecosystems that are often omitted from
theoretical and simulation-based considerations of marine spatial
planning are *technical interactions* and *species on the move*. May
canonical MPA models, informed by planning efforts centered around
relatively static features such as coral reefs, have assumed that
species inhabit a fixed and often uniform (e.g. @hastings2017). In
reality, the habitat of many species are heterogeneous in space, and can
experience both seasonal and directional changes, e.g. climate-change
mediated range shifts.

This reality creates a basic challenge to MPA design, in that given the
need to protect an area less than the total range of a species, the more
complex and dynamics the habitat of the species the more challenging it
will be to identify an area that provides effective protection today and
tomorrow. However, *technical interactions* interact with this spatial
complexity to create another and potentially more difficult challenge.
One of the key questions around spatial management strategies such as
MPAs is to what extent do they *remove* vs *displace* threats.

The potential benefits of MPAs as a bycatch management are complicated
by two key issues: effort displacement and technical interactions. One
of the primary questions around MPAs is to what extent do MPAs remove
versus displace fishing effort. If MPAs remove fishing effort, then
their direct effects on target and bycatch species can only be positive.
If however MPAs displace fishing effort, evaluating their potential
impacts becomes more complicated. The net conservation impact of MPAs
becomes a balancing act between the effects of reduced fishing inside
protected borders and increased fishing intensity outside MPAs. The
outcomes of this displacement can be further complicated by technical
interactions, i.e. the degree to which fishing effort for one species
affects another, particularly when species have markedly different
habitat distributions. For example, @abbott2012 demonstrated that an MPA
designed to protect red king crab (*Paralithodes camtschaticus*) caused
an unintended increase in bycatch of Pacific halibut (*Hippoglossus
stenolepis*) by the displaced bottom-trawl fishery.

Given the complexity of the operating model used here, a complete
sensitivity analysis across all parameters is not practical. Instead, we
focus on the role of life history, fishing pressure, and MPA design.

Each iteration uses one of three species: A stylized tuna modeled after
skipjack tuna (), a stylized marlin modeled after (), and a stylized
shark modeled after (). Each species has all life history parameters
pulled from FishLife (@thorson2020), with the exception of steepness,
set to XX, and fecundity. For the tuna and marlin species, fecundity is
assumed to scale with weight modified by the hyperallometric exponent.
For the shark species, we assume a constant value of six pups per year
at all ages greater than the age at maturity. We assume that tunas have
an unfished biomass of XX, marlins XX, and sharks XX, to reflect a
large, medium, and small population.

For the generalized experiments we only include one fishing fleet. We
assign a price per KG of \$XX for tuna, intended to reflect a low value
high volume fishery, \$XX for marlin for a higher value low volume
fishery, and \$0 for sharks to reflect at true bycatch species. We
assign a selectivity of 60% of length at maturity for skipjack to allow
for some overfishing when F/M is high enough, 70% for marlin, and 90%
for shark.

We ran `r nrow(state_experiments)` state experiments, varying the state
of nature experienced by a simulation. The candidate states include

| State                 | Distribution          | Description                                     |
|------------------|------------------|------------------------------------|
| $\sigma_{centroid}$   |                       | Standard deviation of habitat centroid          |
| $\sigma_{habitat}$    |                       | Standard deviation around centroid              |
| Spatial catchability  |                       | Catchability varies in space                    |
| Spatial allocation    |                       | Fleet allocation strategy                       |
| F/M                   |                       | Fishing mortality relative to natural mortality |
| Adult movement rate   |                       |                                                 |
| Recruit movement rate |                       |                                                 |
| Hyperallometry        |                       | Presence of hyperallometric fec                 |
| DD timing             |                       | Timing of density dependence                    |
| Seasonal Movement     | $\subset[TRUE,FALSE]$ | Seasonal Movement Present                       |

For each of these `r nrow(state_experiments)` state experiments, we then
apply `r nrow(placement_experiments)` placement experiments defined by
an MPA size, an MPA placement strategy, and ...XX

We simulate degrees of species overlap using two parameters, $\sigma_c$
and $\sigma_h$. All species start with the assumption that the centroid
of their preferred habitat occurs in the center-most patch of the two
dimensional system simulated by marlin. For our simulations, we then
generated a random deviation from that default centroid for each species
using $\sigma_c$ in the manner

$$centroid_s \sim normal(center,\sigma_c)$$ where *s* denotes species,
and *center* is the coordinate of the central cell. In this way, the
larger $\sigma_c$ grows, the more variation there is between the
centroid of the preferred habitat for each species.

We then control the spread of a creatures preferred habitat around that
centroid per a Gaussian dispersal kernel in the manner

$$habitat_{p,s} = \frac{1}{\sqrt{2\pi\sigma_h^2}}e^{-\frac{d_p^2}{2\sigma_h^2}}$$

Where $d$ is the euclidean distance from the $centroid_s$ to patch $p$
and $\sigma_h$ controls the dispersal of the habitat around that range.
