---
title: "Revealing Benefits, Costs, and Tradeoffs of Spatial Management Arrising from Coupled Economic and Ecological Dynamics in Marine Systems"
author:
    - Daniel Ovando
address: "8901 La Jolla Shores Drive,La Jolla, CA 92037, USA"
affiliation: "Inter-American Tropical Tuna Comission"
format:
  docx: 
    reference-doc: tuna_template.docx
---

There is a growing movement to expand the use of spatial management measures such as Marine Protected Areas (MPAs) in both coastal and pelagic ecosystems. However, designing effective spatial management strategies is challenging because marine ecosystems are highly dynamic and opaque, and extractive entities such as fishing fleets respond endogenously to ecosystem changes in ways that depend upon ecological and policy context. We present a tool, [marlin](https://danovando.github.io/marlin/), that can be used to efficiently simulate the bio-economic dynamics of coastal and pelagic marine systems in support of both management and research. A key feature of `marlin` is that it allows for realistic simulation of fish movement dynamics in response to changing environmental conditions or foraging opportunities through use of a continuous-time Markov chain process. We demonstrate `marlin's` capabilities in two case studies on the conservation and food production impacts of MPAs: a coastal coral reef and a pelagic tuna fishery. In the coastal coral reef example, we show how heterogeneity in species distributions and fleet preferences can affect distributional outcomes of MPAs. In the pelagic tuna fishery case study, we show how `marlin` can simulate the effects of alternative MPA design strategies on the biomass of pelagic species and the economics of fishing fleets under climate-driven range shifts. Our work demonstrates how intermediate complexity simulation of coupled bio-economic dynamics can help communities predict and potentially manage trade-offs between conservation, fisheries yields, and distributional outcomes of management policies affected by spatial bio-economic dynamics in coastal and pelagic ecosystems. 
