---
title: "Referee Replies"
format: pdf
---
## Notes
- emphasize that this is one model that doesn't capture a lot of stuff

"Spatial Heterogeneous" as definition for the kind of stock structure modeled here, goes from "panmictic" to "Spatial Heterogeneous", per the definitions in bosley et el. 2021. Acutally it can range all the way to metapopulation (set density dependence timing to local, shut down movement at one or more life stages)

## R1


Comments to the Author
This paper presents interesting, well-documented, and useful modeling software for spatial management of fisheries targeting multiple non-interacting species. I could see it becoming a go-to for both fisheries scientists and advanced fisheries courses. It should be published following minor revisions.

**We thank the reviewer for their helpful comments. **

My main suggestion for revision is to explain and emphasize the case-study results a bit more. Ultimately, the insights from the case studies will be one of the main things that convince readers to use the model. For example, what is the intuition behind the results in Figure 5A, showing target-fishing design being much more robust to range shifts than rate design? More generally, what are the most important things we should take away from the case studies?

**We have added a specific "Insights from Case Studies" section to the discussion to provide clearer insights from our results.**

Second, the authors should clarify that their model has both strategic and tactical uses, not just tactical. There are a lot of basic strategic questions that could be asked with this model. The case studies are arguably strategic as much or more so than they are tactical.

**We have added a "General Recommendations for using `marlin`" section to the discussion, in which we have emphasized this point amount others.** 


Minor comments:
Line 116: typo ‘th’.
**Corrected.**

Line 169: This seems like a potentially strong assumption that could artificially eliminate weak-stock-strong-stock tradeoffs. This should be discussed and justified.

**This is a very good point, particularly as 0% discard mortality is clearly the exception rather than the rule. We agree that this is too strong of assumption to use in many cases, and are working to implement both a discard rate and a discard mortality function into the model. However, as seasonal management is not a key feature of the model at this time, and is not used in our case study, we have elected to remove the mention of seasonal closures for now from the manuscript, though we are pursuing the addition of this feature in the package itself.**

XX Probably not going to do this yet since it is a pain in the ass XX. 
**To address this concern, we have modified the model such that "closed" seasons are now implemented by a multiplier on fishing mortality that can range from 0 to 1. When the multiplier is set to 0, the closed season is 100% effective (i.e. no discard mortality). Setting the multiplier to 0.5 instead reduces F by 50%, reflecting a 50% discard mortality rate**


Line 280: missing period.

**Corrected.**


Line 283: that is a very nice model feature.

**We are glad the reviewer finds this feature helpful, many thanks to the folks at FishBase and Thorson's prior work with FishLife for making it possible.**

Line 301: Is omitting advection only a significant limitation for drifting species like plankton or jellyfish, or is it also a limitation for large pelagics that concentrate at SST fronts?

**Good question. A strength of the CTMC approach is that, given sufficient data, one can separate out the components of movement into advection, taxis, and diffusion. Having this knowledge is certainly interesting, but from a simulation perspective is less critical. One could simulate the dynamics of a large pelagic concentrating at an SST front using simply the taxis matrix in `marlin`; while the SST fronts themselves are clearly a partial product of advective forces, so long as we know where they are, we can just pass their location to marlin and the fish will go there. What would be missing there might be some timing dynamics whereby a fish might take longer to get to ideal habitat when fighting against a current than with it. The biggest limitation of omitting the advection matrix at this point is the potential to overlook cases where a current is strong enough to essentially serve as a barrier preventing an organism from reaching preferred habitat that it otherwise would go to under the taxis + diffusion model. We have clarified this in the text of the discussion, and pointed out the value of research into the importance of advective forces as well. **

Line 473: Typo: “Do” -> “Due”.
**Corrected.**


##R2

FaF-23-Apr-OA-149 Review 02 Aug 2023
Summary
This study presents a bio-economic modeling tool aimed to provide a tractable, efficient, tactical management simulation framework for marine fisheries. It seeks to complement earlier, similar, models which are highly complex, bespoke, or overly-generalized. Case study applications to a coral reef and pelagic ecosystem is presented. The study conclusions does not evaluate spatial management paradigms per se, but rather illustrate the value of “sufficiently realistic” biodynamic models for policy evaluation.


This model and paper provide the following novel contributions:
1) the modeling framework allows users to test either eliminating or displacing fishing effort given the placement of an MPA; ignoring these alternative possibilities was the cause of much scandal and scientific misinformation in recent MPA analyses,

**It certainly has been, we are glad the reviewer finds this feature useful**

2) a wise avoidance of the calculation of equilibrium-based quantities for spatio-temporal models, precluding scientists’ conclusion that certain policies do or do not meet management targets (as these are not definable under such conditions), and

**Though dynamic and spatially explicit reference points are certainly an area of interesting research going forward.**


3) an explicit manner of investigating MPA effectiveness in the context of range shifts, which are important for climate-enhanced fishery management.


I recommend publication with minor revision.


Major Comments
This is a well-written paper, and I appreciated that the methods are clear and high-level, with minimal equations. There are two central things that need to be addressed in the document, which would bolster and clarify how marlin fits into the spatial modelling world, and how we can interpret the results. I believe these can be readdressed through a fairly simple simulation exercise and the addition of a few paragraphs to the methods & discussion.

Most importantly, the reader wants to know whether marlin is providing insights consistent with our understanding of how population and fishery dynamics behave in space, and whether the reader has enough information to make it worth testing the model on their fishery. If the aim is for this model to be used by global communities with little data or information about their fishery, please discuss if/how the model can be simplified to provide insights useful in the absence of key processes (i.e., selectivity). 

**We have added a "General Recommendations for using `marlin`" section to the discussion, in which we have emphasized this point amount others.** 


How dependent is the simulation accuracy on full confidence in the inputs? I am not requesting a full misspecification analysis. Rather, please illustrate or discuss how the results of the coral reef case study, for example, might change if we are incorrect that Fleet Two has dome-shaped selectivity. We know this to be problematic in spatial models. How do your findings compare to earlier examinations of mis- specified selectivity in spatial context, e.g. works by Aaron Berger and Lynn Waterhouse?

**We have added a "General Recommendations for using `marlin`" section to the discussion, in which we have emphasized this point amount others.** 

XX I still need to integrate some more of these XX s

Bosley, Katelyn M., Amy M. Schueller, Daniel R. Goethel, Dana H. Hanselman, Kari H. Fenske, Aaron M. Berger, Jonathan J. Deroba, and Brian J. Langseth. “Finding the Perfect Mismatch: Evaluating Misspecification of Population Structure within Spatially Explicit Integrated Population Models.” Fish and Fisheries 23, no. 2 (2022): 294–315. https://doi.org/10.1111/faf.12616.


Berger, Aaron M., Daniel R. Goethel, Patrick D. Lynch, Terrance Quinn, Sophie Mormede, Jeremy McKenzie, and Alistair Dunn. “Space Oddity: The Mission for Spatial Integration.” Canadian Journal of Fisheries and Aquatic Sciences 74, no. 11 (November 2017): 1698–1716. https://doi.org/10.1139/cjfas-2017-0150.


Berger, Aaron M., Michael L. Jones, Yingming Zhao, and James R. Bence. “Accounting for Spatial Population Structure at Scales Relevant to Life History Improves Stock Assessment: The Case for Lake Erie Walleye Sander Vitreus.” Fisheries Research 115–116 (March 1, 2012): 44–59. https://doi.org/10.1016/j.fishres.2011.11.006.

Berger, Aaron M, Jonathan J Deroba, Katelyn M Bosley, Daniel R Goethel, Brian J Langseth, Amy M Schueller, and Dana H Hanselman. “Incoherent Dimensionality in Fisheries Management: Consequences of Misaligned Stock Assessment and Population Boundaries.” ICES Journal of Marine Science 78, no. 1 (February 1, 2021): 155–71. https://doi.org/10.1093/icesjms/fsaa203.

Waterhouse, Lynn, David B. Sampson, Mark Maunder, and Brice X. Semmens. “Using Areas-as-Fleets Selectivity to Model Spatial Fishing: Asymptotic Curves Are Unlikely under Equilibrium Conditions.” Fisheries Research, SI: Selectivity, 158 (October 1, 2014): 15–25. https://doi.org/10.1016/j.fishres.2014.01.009.


- Add discussion to the effect of "marlin has a lot of options. A recommended use case would be to try and narrow down things that are "known", and then focus sensitivity runs on outcomes that are uncertain and likely to be important. For example, testing the sensitivity of outcomes to misspecified selectivity curves

**We have added a "General Recommendations for using `marlin`" section to the discussion, in which we have emphasized this point amount others.** 


The value of this contribution would be stronger if you directly compared the findings from your case studies with similar works. For example, there have been several studies (empirical and simulation- based) examining MPAs and coral reef ecosystems. Several have found confounding effects of MPA closures, often caused by inter-species interactions, which I recognize are not modeled here. Does marlin provide similar insights on less information (i.e. without predator dynamics)?


**case study section literature time here. Really struggling with this one. Thoughts on how to address?**


Of secondary importance, I am not sure I agree that marlin follows the MICE paradigm. Much of the model specification (I’m thinking movement especially) is highly granular even for well-studied fisheries. 

**We have removed the reference to MICE models per say..**

It is common for tactical applications to model irregular polygons of distinct biological and/or political attributes, connected by a user-input matrix of movement values. Confirm whether the current setup requires individual patches to share biological information and the harvest strategies among them. Discuss how spatial heterogeneity in population demography can impact model results.

**This is a very good point; spatio-temporal variation in population demography (and regulation) can be extremely important and is not captured here. `marlin` assumes that while habitat can vary in space and time, population processes are constant within a species. That being said,  users could treat different morphs of a population as separate species with different habitats. For example, if an invertebrate species grows at a different rate in warmer coastal waters than cooler deeper waters, these could simply be modeled as two separate species with different growth parameters. However, the model would not then allow for interbreeding of those morphs..xx** Cite @waterhouse2014 here, need to find where to cite and add to paper XX

see "finding the perfect mismatch bosley paper" for discussions around frequency of spatial complexity paired with frequency of ignoring it

Minor Comments
I recognize the authors didn’t want to detail every aspect of the model specifications, but these are things the reader might want to know from the outset:

L106 “10 x 10 patch system” – units? what is a “patch” here? (related to point above about what info is shared within a patch)

**Users on standard computers should be able to simulate one age-structured population distributed across spatial surface represented by a ten by ten grid of cells over 20 years in fractions of a second**

L157 you mention size limits as a potential harvest control – but don’t say that size is also represented in the pop dynamics until much later

**We have now clarified in the opening description that the model also tracks lengths at age**.

Model Summary – somewhere early in here, confirm that there is no estimation/conditioning capacity within marlin (to discourage folks from thinking they might be able to run assessments within it, for example). Add a sentence or two near the beginning describing what the user must provide to the model, and state that meta-analyses like FishLife will be consulted in their absence.

**We have added a few sentences to the model summary section describing the minimum inputs needed, and making the important point that there is no estimation feature built into marlin**



L232 Related to above: I see the description of the tuning settings. When total SSB is specified in the context of MPA, how is Q adjusted? Does this step interact with the option to either displace or turn off effort outside of an MPA?

**We have clarified in the text that "`marlin` allows users to specify a target unfinished spawning stock biomass ($SSB0$), which will be achieved by tuning the total unfished recruitment (R0), given the remaining life history parameters and independent of any characteristics of the fishing fleets.". We have also clarified in the "tuning fishing fleet parameters" section that all tuning is done conditional on the underlying population dynamics.**

L259 what sort of time scale is needed for this approximation to be true? 

**We have clarified in the text that "The timeline required for the fleets to reach an equilibrium distribution will vary and depend on factors such as the population dynamics of the species in question (e.g. movement, habitat heterogeneity, growth rates, density dependence) and the number and degree of competition across fleets. Users should explore different simulation times to ensure that any results they wish to use are not simply a reflection of the fleet dynamics fluctuating on their way to an equilibrium condition. "**

L310 “that the model is running under” – rephrase

**Clarified**. 

L363 be consistent about capitalization of SSB

**Fixed**

L447 too many quotes in this section

**Removed**

L493 quarterly timestep? Only one year (four seasons total)?

**We have clarified that the simulation runs for 100 years in time steps of quarter years (i.e. four seasons per year)**

Figure 3 I’d prefer this to have the same colorscale as Figure 1; do a panel for each condition, don’t overlay them.

**We have changed Figure 3 to reflect the same format as Figure 1, and agree it is much improved, thank you!**


L534 Do they actually mask them, or do interesting dynamics underlie these findings? Add a sentence here what users should do with this info (i.e. be sure to look at the tradeoffs one by one – is there functionality in marlin to do so, such as automated plots or summary tables?)

**Good point, we clarify that "These macro-level changes in total yield and conservation are the result of interesting internal dynamics that `marlin` allows users to explore through output tables at the level of individual species and fleets." We do not specify specific functions within the marlin package here as the details of those may evolve over time.**

FIG 4. The results state three MPA strategies were used: spawning ground, spawning aggregation, and target fishing, but I only see two here.

**We have fixed this typo (we had accidentally refered to the same policy by two different names).**

FIG 4C This figure is confusing; I’m not clear what the skinny short lines are. The caption doesn’t clarify which color of label corresponds to which % change in yield; instead just use a colored point for these values.

**We have modified Figure 4C and we hope the reviewer finds it clearer now. Much of the visual clutter of Fig 4C was due to the long tail to the right of high SSB increases and catch decreases that occured once MPA size approaches 100%. To help illustrate the more interesting points of the results, we have limited the figure to MPA sizes <= 65%, and removed the text labels for MPA sie and replaced them with colored points to indicate MPA size along each of the MPA design strategy curves.**
